# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'aws'
            options:
                client: 'app.images.s3'
                bucket: '%env(resolve:BUCKET)%'
                prefix: '%env(resolve:PREFIX)%'
#                options: ''
#                streamReads: ''

