# api/config/api_platform/member.yaml
App\Entity\Member:
  attributes:
    normalization_context:
      groups: [member_read]
  collectionOperations:
    get_last_post:
      method: GET
      path: /member
      controller: App\Action\Post\LastPost
      deserialize: false
      normalization_context:
        groups: [member_read]
      openapi_context:
        summary: Lista miembros de la iglesia
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: string
                    firstName:
                      type: string
                    lastName:
                      type: string
    post:
#      method: POST
#      security: is_granted("CATEGORY_CREATE")
#      denormalization_context:
#        groups: ['member_write']

  itemOperations:
    get:
      method: GET
      security: is_granted("member_read", object)

  properties:
    userMedia:
      subresource:
        resourceClass: App\Entity\SocialMedia
        collection: true
        maxDepth: 1