# api/config/api_platform/member.yaml
App\Entity\Member:
  attributes:
    normalization_context:
      groups: [member_read]
  collectionOperations:
#    get:
#      method: GET
#      path: /member
##      controller: App\Action\Post\LastPost
#      deserialize: false
#      normalization_context:
#        groups: [member_read]
#      openapi_context:
#        summary: Lista miembros de la iglesia
#        responses:
#          200:
#            description: OK
#            content:
#              application/json:
#                schema:
#                  type: object
#                  properties:
#                    id:
#                      type: string
#                    firstName:
#                      type: string
#                    lastName:
#                      type: string
    post:
      method: POST
      path: /members
#      security: is_granted("CATEGORY_CREATE")
      denormalization_context:
        groups: ['member_read']

    upload_file:
      method: POST
      path: /member/{id}/upload_file
      controller: App\Action\Member\UploadFIle
      deserialize: false
      openapi_context:
        summary: Upload a file attached to a movement
        requestBody:
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  file:
                    type: string
                    format: binary

  itemOperations:
    get:
      method: GET
      security: is_granted("member_read", object)





  properties:
    userMedia:
      subresource:
        resourceClass: App\Entity\SocialMedia
        collection: true
        maxDepth: 1