# api/config/serialization/coexistenceSituation.yaml
App\Entity\CoexistenceSituation:
  attributes:
    id:
      groups: ['coexistenceSituation_read', 'familyMember_read']
    name:
      groups: ['coexistenceSituation_read', 'familyMember_read']