# api/config/serialization/relationalSituation.yaml
App\Entity\RelationalSituation:
  attributes:
    id:
      groups: ['relationalSituation_read']
    name:
      groups: ['relationalSituation_read', 'familyMember_read']
#    identifier:
#      groups: ['relationalSituation_read']
#    description:
#      groups: ['relationalSituation_read']
